### ISSUE TITLE
What does c_m and c_n mean? Does the dimension change when the tensor come cross the layer?

### ISSUE THREAD

**Issue by ZealACMer** [gjylt/DoubleAttentionNet#1]
![image](https://user-images.githubusercontent.com/16794553/61146887-a604c880-a50d-11e9-82f2-3f78c7e95184.png)
My question is what does c_m and c_n mean which are shown in the above picture. And another question is whether the dimension of tensor changed when it cross the double attention layer.
Thank you so much for you kind help.

**Comment by gjylt** [comment]
you can find this in figure.1 of paper. c_m is the output channel number of conv φ, c_n is the output channel of conv θ and conv ρ. In Ablation Studies part, the writer commad set those channel number to be 1/4 of the number of input channels.

**Comment by ZealACMer** [comment]
Thank you so much for your reply. does the dimension of tensor change when the input tensor cross the double attention layer, thank you very much.

**Comment by gjylt** [comment]
> Thank you so much for your reply. does the dimension of tensor change when the input tensor cross the double attention layer, thank you very much.

yes, in this version, the output channel is the c_m. Compare with the paper，this vesion lack of the extension and concat part. You can add an 1x1x1 conv to be as extension part, and plus the input and the extensioned part to be the final output.

**Comment by ZealACMer** [comment]
Thank you so much for your kind help. Thank you very much.
